error: com.bilibili.dagger.component.MainActivityComponent (unscoped) cannot depend on scoped components
(cherry picked from commit dbaf71971043c55185a548128fb7de242185c8cc)